name: gee_dataset_catalog_metadata
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  # GEE deps:
  # - earthengine-api
  # - py6s
  # - geemap
  - pip
  - pip:
    - pandas~=1.3.3
    - parse~=1.19.0
    - pyyaml~=6.0
